### ISSUE TITLE
update request

### ISSUE THREAD

**Issue by PabloLION** [PolyKen/AlphaRenju_Zero#6]
the dependencies of this project has updated and met a huge change in their API, due to this change I'm trying to update this repo to make it compatible with python3.11 due to the removal of setuptools.

During this process, I find some problems like 

1. mode=2.5

2. `save_weights` called (in network.py) by
  
  ```py
      def save_model(self):
          """save model para to file"""
          self._model.save_weights(self._net_para_file)
  ```
  
  requires `.weights.h5` yet while `self._net_para_file` doesn't have that suffix.
  
3. model data problem
  both `model_b_15.h5` and `model_w_15.h5` has 21 layers and load model needs a 18-layers weight.

Is this repo still under maintenance? I'd appreciate if there are (high level) docs of this project.
Thanks in advance.

**Comment by PolyKen** [comment]
Hi Pablo,

The project is not under maintenance now. It did not make use of any popular RL framework and its structure was not well arranged as I had little knowledge about RL then. Thank you for your interests but I think it would be better to refer to other repo on github that replicates alphazero algorithm.

________________________________
发件人: Pablo LION ***@***.***>
发送时间: 2024年10月3日 08:59
收件人: PolyKen/15_by_15_AlphaGomoku ***@***.***>
抄送: Subscribed ***@***.***>
主题: [PolyKen/15_by_15_AlphaGomoku] update request (Issue #6)


the dependencies of this project has updated and met a huge change in their API, due to this change I'm trying to update this repo to make it compatible with python3.11 due to the removal of setuptools.

During this process, I find some problems like

  1.  mode=2.5

  2.  save_weights called (in network.py) by

    def save_model(self):
        """save model para to file"""
        self._model.save_weights(self._net_para_file)

requires .weights.h5 yet while self._net_para_file doesn't have that suffix.

Is this repo still under maintenance? I'd appreciate if there are (high level) docs of this project.
Thanks in advance.

―

**Comment by PabloLION** [comment]
Thanks for the reply!

After a deeper look, although this seems to be a student project, it's still great, as it works as intended and comes with an intuitive reactive GUI. I'll try to improve the code or just start a new project.

Thanks again for the work.
